project:
  type: website

website:
  title: "Navigation through Life"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/athira-anil2327
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: darkly
    css: styles.css



